name: Frontend Staging Deployment

on:
  push:
    branches: [staging]
    paths: ['client/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd client
          docker build -t frontend:staging .
          ssh -i ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.STAGING_EC2_HOST }} \
            "docker stop frontend || true && \
             docker run -d -p 3000:3000 --name frontend --restart unless-stopped frontend:staging"
      - name: Run Tests
        run: |
          ssh -i ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.STAGING_EC2_HOST }} \
            "curl -f http://localhost:3000 || exit 1"
