name: Frontend Dev Deployment

on:
  push:
    branches: [dev]
    paths: ['client/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd client
          docker build -t frontend:dev .
          ssh -i ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.DEV_EC2_HOST }} \
            "docker stop frontend || true && \
             docker run -d -p 3000:3000 --name frontend --restart unless-stopped frontend:dev"
