name: Backend CI/CD

on:
  push:
    branches: [dev, staging, main]
    paths: ['server/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Similar steps as frontend, but:
      # - Port 5000 instead of 3000
      # - Add DB environment variables
      # - Different EC2 hosts for each environment
