name: Backend Prod Deployment

on:
  push:
    branches: [main]
    paths: ['server/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: trstringer/manual-approval@v1  # Manual approval
      - run: |
          cd server
          docker build -t backend:prod --build-arg DB_HOST=${{ secrets.DB_PROD_HOST }} .
          ssh -i ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.PROD_EC2_HOST }} \
            "docker stop backend || true && \
             docker run -d -p 5000:5000 -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} --name backend --restart unless-stopped backend:prod"
