name: Backend Dev Deployment

on:
  push:
    branches: [dev]
    paths: ['server/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd server
          docker build -t backend:dev .
          ssh -i ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.DEV_EC2_HOST }} \
            "docker stop backend || true && \
             docker run -d -p 5000:5000 --name backend --restart unless-stopped backend:dev"
